### ISSUE TITLE
Differences between Personalization Tool and Manager regarding Challenge-Response mode HMAC-SHA1 (fixed 64 byte input)

### ISSUE THREAD

**Issue by mrclschstr** [Yubico/yubikey-personalization-gui#86]
Hello everybody,

first of all, I hope that I picked the right repository for this kind of issue. I'm crossposting this because of an issue we experienced using the Yubikey with KeePassXC (cross-platform port of KeePass): https://github.com/keepassxreboot/keepassxc/issues/1734.

We were discussing some kind of "KeePassXC Recovery Mode" in case of a stolen/lost Yubikey. Some ingenious users found a way to extract the Challenge from the database, which is used for the Challenge-Response procedure to unlock the database: https://github.com/keepassxreboot/keepassxc/issues/1734#issuecomment-416029033.

The anomaly we detected is that the Yubikey Response seems to depend on the tool it was programmed (Yubikey Manager vs. Yubikey Personalization Tool). Programming the Yubikey with Challenge-Response mode HMAC-SHA1 (fixed 64 byte input!) using the Yubikey Personalization Tool seems to be incompatible using "standard HMAC-SHA1 algorithms" (e.g. openssl). Using variable input seems to work: https://github.com/keepassxreboot/keepassxc/issues/1734#issuecomment-486418757.

I hope that I have described everything correctly. Is there any known bug regarding this?

**Comment by klali** [comment]
The flag that can affect this is the hmac-lt64 in which mode the yubikey receives a challenge of 1-63 byte, if this flag is not set it operates on a 64 byte challenge. In this tool that flag is called "variable input"/"fixed 64 byte input". In the lt64 mode the challenge is truncated based on the last character so "aaaaff...ffff" is truncated to "aaaa", without this flag that is used as is as the challenge.

**Comment by mrclschstr** [comment]
To be more precise, it seems to me that writing a fixed length Secret Key using the Yubikey Personalization Tool is not working correctly. Using a back-to-back test with the Yubikey Manager and openssl produces a different response. Seems like a bug to me.

**Comment by klali** [comment]
In the fixed mode the challenge is always 64 bytes (typically padded out with zeroes if you try to use something shorter).

If a slot is programmed in fixed mode with the key 01020304 something like:
$ ykchalresp -2 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

and:
echo -n "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | openssl dgst -sha1 -mac hmac -macopt hexkey:01020304

should give the same result (13dd5a4ea18dbf51d0a469b044a82dbdb3317db5).

**Comment by mrclschstr** [comment]
I finally found some time to test it a bit further. I set up my Yubikey using the _Yubikey Personalization Tool_ with a Secret Key (20 bytes Hex, meaning fixed 64 byte input). When I do your mentioned test, I get the following results:

```
$ ykchalresp -1 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
063d09573c8209ebc5198a8362759e824055269e

$ echo -n "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | openssl dgst -sha1 -mac hmac -macopt hexkey:<SECRET_KEY>
(stdin)= 063d09573c8209ebc5198a8362759e824055269e
```

When I set up my Yubikey with **the same Secret Key** using the _Yubikey Manager_, I get the following results:

```
$ ykchalresp -1 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
77e364c820714d556f723b2b8b79c90126686fb4

$ echo -n "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | openssl dgst -sha1 -mac hmac -macopt hexkey:<SECRET_KEY>
(stdin)= 063d09573c8209ebc5198a8362759e824055269e
```

Still seems like a bug to me or am I making a mistake during setup? Does it make a difference using a space separated secret key (see: https://github.com/mmcguill/Strongbox/issues/95#issuecomment-504238115)?

**Comment by dainnilsson** [comment]
The issue isn't with the length of the secret being used, it's with the length of the challenge. At time of programming the YubiKey, you need to specify whether challenges will be less than 64 bytes, or exactly 64 bytes,. This is done by setting the hmac-lt64 (less than 64) switch on or off. 

ykpersonalize exposes this flag as a command line argument. For the example you've provided, using the challenge of `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (64 bytes), the flag should NOT be set (since the challenge is NOT less than 64 bytes), and the resulting response will match that of openssl.

Now, here's why you're getting a different result when programming with `ykman`: YubiKey Manager ALWAYS sets the hmac-lt64 flag when programming a challenge-response secret. This means that the configuration will expect to receive challenges which are shorter than 64 bytes, which causes the challenge you are sending to be incorrectly interpreted by the YubiKey, as it will attempt to unpad the value to the correct size.

It's a bit convoluted, but I hope that explanation makes sense.

**Comment by mrclschstr** [comment]
Explains a lot, thanks!

**Comment by gitbabd** [comment]
Updated my system to xubuntu 24.04 and couldn't install yubikey-personalization-gui (no packages). Can't also install manually because dependencies are missing - but this is another issue.

We have many yubikeys that have been provisioned with yubikey-personalization-gui with HMAC-SHA1 Challenge Response (on slot 2) with "Fixed 64 byte input".

I tried yubico-authenticator which recognizes the yubikey -> Challenge Response -> put the 40 character secret and Saved. Slo2 2 got written successfully but it does not work (with KeepassXC).

I then tried 
`ykman otp chalresp 2 --touch`
Could save the secret but again error with KeepassXC.

Now, the question is which tool can I use to produce a yubikey that has to be configured with a fixed 64byte secret with challenge response?
